version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
        #artifacts:
        #  files:
        #    - target/aws-codebuild-maven-1.0-SNAPSHOT.war
        #  discard-paths: yes
